### PR TITLE
replaced map().sum() with fold

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
Most of the changes are cause of the formater sorry

### CODE REVIEW

**Comment by ChristopherBiscardi** [comment]
> Most of the changes are cause of the formater sorry

no worries. I'll stick a rustfmt.toml in the root of the project so people have the right formatting stuff.

What's the motivation for moving from .map.sum to fold here?

**Comment by Vilhelm-Ian** [comment]
Not sure if it's faster. Probably once compiler optimizations are made it will compile to the same assembly. I just think it's better. Since you don't have to create an array and then iterate through it to get the sum. This just does it one go

**Comment by DanikVitek** [comment]
> Since you don't have to create an array and then iterate through it to get the sum. This just does it one go

Iterators are built in a way that this would take one pass in any case. Iterators are lazy, so all `filter`s and `map`s are done once per the call to `.next()`. Unlike, for example, in JavaScript, where every `.map` and `.filter` call creates a new array.

**Comment by Vilhelm-Ian** [comment]
@DanikVitek if I did 
```rust
(0..5).map(|x| { 
println!("hello");
x * 2
}).for_each(|x| println!("world"));
```
wouldn't the output be
```
hello
hello
helllo
hello
hello
world
world
world
world
world
```

**Comment by ChristopherBiscardi** [comment]
I updated the formatting so that the PR would have less noise

**Comment by Vilhelm-Ian** [comment]
thanks @ChristopherBiscardi can I clean up my day 5 code ask you to take a look when you have time(since you are also busy with bevy game jame and advent of code currently)

**Comment by ChristopherBiscardi** [comment]
@Vilhelm-Ian sure, happy to take a look when I have time

**Comment by Vilhelm-Ian** [comment]
@ChristopherBiscardi I just realized something .iter().map().sum() might not allocated more memory than .iter().fold() but it seems that's not the case for .par_iter().map().sum() and .par_iter().fold().reduce(). The first one makes my pc crash

**Comment by ChristopherBiscardi** [comment]
@Vilhelm-Ian While using rayon *does* mean that you will be iterating on more items in parallel, and thus could tip the limit of your PC if the individual `.map` calls are big there are two important notes:

First, rayon's [ParallelIterator::map](https://docs.rs/rayon/1.8.0/rayon/iter/trait.ParallelIterator.html#method.map) is it's own and is not the same as [Iterator::map](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.map), as shown here: https://rust-lang-nursery.github.io/rust-cookbook/concurrency/parallel.html#map-reduce-in-parallel

Second, rayon's docs say .map.reduce and .sum [are effectively the same](https://docs.rs/rayon/1.8.0/rayon/iter/trait.ParallelIterator.html#method.sum) so I would be surprised if one caused your computer to crash and the other didn't.

> Basically equivalent to self.reduce(|| 0, |a, b| a + b), except that the type of 0 and the + operation may vary depending on the type of value being produced.

The rayon docs also [have information relating to fold vs map/reduce](https://docs.rs/rayon/1.8.0/rayon/iter/trait.ParallelIterator.html#fold-vs-mapreduce) which should be reviewed.

**Comment by Vilhelm-Ian** [comment]
@ChristopherBiscardi I didn't mention this to support my pull request. Just wanted to share something I realized about .iter.map vs .par_iter.map

**Pull request closed without merging**
